version: '3.8'

services:
  ekpabot-go:
    build:
      context: .
      dockerfile: Dockerfile.go
    container_name: ekpabot-go
    restart: unless-stopped
    volumes:
      - ./configs:/app/configs:ro
    environment:
      - TZ=Europe/Istanbul
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
