package com.qeeqez.ekpaantalyabot.constants;

public enum InlineButtonEnum {

    MAIN_MENU_BUTTON,

    ADDRESS_BUTTON,

    // Our Chats
    OUR_CHATS_BUTTON,
    BLOCKS_CHAT_BUTTON,

    // Directions
    DIRECTIONS_BUTTON,
    RESIDENCE_CAFE_BUTTON,
    MARKETS_BUTTON,
    ALL_MARKETS_BUTTON,

    PRINT_AND_PHOTO_BUTTON,
    BARBER_BUTTON,
    SHOPS_BUTTON,
    SHOPPING_CENTERS_BUTTON,

    // Phones
    PHONE_NUMBERS_BUTTON,
    EKPA_MANAGEMENT_BUTTON,
    EMERJENCY_BUTTON,
    OTHER_PHONES_BUTTON,

    // Embassy
    EMBASSY_BUTTON,
    RUSSIA_EMBASSY_BUTTON,
    UKRAINE_EMBASSY_BUTTON,
    KAZAKHSTAN_EMBASSY_BUTTON,
    BELARUS_EMBASSY_BUTTON,

    // Useful Info
    USEFUL_INFO_BUTTON,
    MANAGEMENT_OFFICE_BUTTON,

    // How To Pay
    HOW_TO_PAY_BUTTON,
    HOW_TO_PAY_AIDAT_BUTTON,
    HOW_TO_PAY_CONDITIONER_BUTTON,
    HOW_TO_PAY_ELECTRICITY_BUTTON,
    HOW_TO_PAY_WATER_BUTTON,
    HOW_TO_PAY_INTERNET_BUTTON,

    // How To Connect
    HOW_TO_CONNECT_BUTTON,
    HOW_TO_CONNECT_DASK_INSURANCE_BUTTON,
    HOW_TO_CONNECT_ELECTRICITY_BUTTON,
    HOW_TO_CONNECT_WATER_BUTTON

}
