package com.qeeqez.ekpaantalyabot.constants;

public enum InlineButtonEnum {

    MAIN_MENU_BUTTON,

    ADDRESS_BUTTON,

    // Our Chats
    OUR_CHATS_BUTTON,
    BLOCKS_CHAT_BUTTON,

    // Directions
    DIRECTIONS_BUTTON,
    RESIDENCE_CAFE_BUTTON,
    RESIDENCE_CAFE_WIFI_BUTTON,

    MARKETS_BUTTON,
    ALL_MARKETS_BUTTON,

    PRINT_AND_PHOTO_BUTTON,
    POST_OFFICE_BUTTON,
    TAX_OFFICE_BUTTON,


    CITY_HALL_BUTTON,
    POPULATION_OFFICE_BUTTON,
    MIGRATION_OFFICE_BUTTON,

    BARBER_BUTTON,
    SHOPS_BUTTON,
    SHOPPING_CENTERS_BUTTON,

    // Phones
    PHONE_NUMBERS_BUTTON,
    EKPA_MANAGEMENT_BUTTON,
    EMERJENCY_BUTTON,
    OTHER_PHONES_BUTTON,

    // Embassy
    EMBASSY_BUTTON,
    RUSSIA_EMBASSY_BUTTON,
    UKRAINE_EMBASSY_BUTTON,
    KAZAKHSTAN_EMBASSY_BUTTON,
    BELARUS_EMBASSY_BUTTON,

    // Ekpa Info
    INFO_EKPA_BUTTON,
    MANAGEMENT_OFFICE_BUTTON,

    // How To Pay
    HOW_TO_PAY_BUTTON,
    HOW_TO_PAY_AIDAT_BUTTON,
    HOW_TO_PAY_CONDITIONER_BUTTON,
    HOW_TO_PAY_ELECTRICITY_BUTTON,
    HOW_TO_PAY_WATER_BUTTON,
    HOW_TO_PAY_PHONE_AND_INTERNET_BUTTON,

    // How To Connect
    HOW_TO_CONNECT_BUTTON,
    HOW_TO_CONNECT_DASK_INSURANCE_BUTTON,
    HOW_TO_CONNECT_ELECTRICITY_BUTTON,
    HOW_TO_CONNECT_WATER_BUTTON,
    HOW_TO_CONNECT_INTERNET_BUTTON,

    // Useful Info
    INFO_USEFUL_BUTTON,

    EDEVLET_BUTTON,

    TRANSPORT_BUTTON,
    BUS_BUTTON,
    ANTALYA_CARD_BUTTON,
    TAXI_BUTTON,
    KICK_SCOOTER_BUTTON,


    TAX_NUMBER_BUTTON,
    ADDRESS_NUMARATAJ_BUTTON,
    ADDRESS_REGISTRATION_BUTTON,

    CAR_FINE_BUTTON,


    PHONE_UNLOCK_BUTTON,
    PHONE_UNLOCK_SIM_BUTTON,
    PHONE_UNLOCK_IMEI_BUTTON,
    PHONE_UNLOCK_IMEI_FREE_BUTTON,
    PHONE_UNLOCK_IMEI_PAID_BUTTON,


    AID_KIT_BUTTON,
    AMBULANCE_BUTTON,
    MEDICINE_BUTTON,
    PHARMACIES_BUTTON,

    HOSPITALS_BUTTON,
    POLYCLINIC_BUTTON,


    DELIVERY_BUTTON,
    FOOD_DELIVERY_BUTTON,
    PRODUCTS_DELIVERY_BUTTON,
    GOODS_DELIVERY_BUTTON,
}
