version: "1.0"

screens:
  - id: "DIRECTIONS"
    text: "*Что рядом?*"
    parse_mode: "MarkdownV2"
    inline_keyboard:
      rows:
        - buttons:
            - id: "markets"
              text: "🧺 Рынки"
              type: "callback"
              callback: "MARKETS_BUTTON"
            - id: "shops"
              text: "🍎 Магазины"
              type: "callback"
              callback: "SHOPS_BUTTON"
            - id: "shopping_centers"
              text: "🛍 ТЦ"
              type: "callback"
              callback: "SHOPPING_CENTERS_BUTTON"
        - buttons:
            - id: "print_photo"
              text: "🖨️ Печать и Фото 📸"
              type: "callback"
              callback: "PRINT_AND_PHOTO_BUTTON"
        - buttons:
            - id: "barber"
              text: "✂️ Барбершопы"
              type: "callback"
              callback: "BARBER_BUTTON"
        - buttons:
            - id: "tax_office"
              text: "💸 Налоговая"
              type: "callback"
              callback: "TAX_OFFICE_BUTTON"
            - id: "post_office"
              text: "✉️ Почта"
              type: "callback"
              callback: "POST_OFFICE_BUTTON"
        - buttons:
            - id: "city_hall"
              text: "🏛 Belediye"
              type: "callback"
              callback: "CITY_HALL_BUTTON"
            - id: "population_office"
              text: "🧑‍💼 Nufus"
              type: "callback"
              callback: "POPULATION_OFFICE_BUTTON"
            - id: "migration_office"
              text: "👮 Goc"
              type: "callback"
              callback: "MIGRATION_OFFICE_BUTTON"
        - buttons:
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "MARKETS_BUTTON"
        target: "MARKETS"
      - callback: "SHOPS_BUTTON"
        target: "SHOPS"
      - callback: "SHOPPING_CENTERS_BUTTON"
        target: "SHOPPING_CENTERS"
      - callback: "PRINT_AND_PHOTO_BUTTON"
        target: "PRINT_AND_PHOTO"
      - callback: "BARBER_BUTTON"
        target: "BARBER"
      - callback: "TAX_OFFICE_BUTTON"
        target: "TAX_OFFICE"
      - callback: "POST_OFFICE_BUTTON"
        target: "POST_OFFICE"
      - callback: "CITY_HALL_BUTTON"
        target: "CITY_HALL"
      - callback: "POPULATION_OFFICE_BUTTON"
        target: "POPULATION_OFFICE"
      - callback: "MIGRATION_OFFICE_BUTTON"
        target: "MIGRATION_OFFICE"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "DIRECTIONS_SITE"
    text: "*🗺 Карта объектов*"
    parse_mode: "MarkdownV2"
    inline_keyboard:
      rows:
        - buttons:
            - id: "residence_cafe"
              text: "☕️ Residence Cafe"
              type: "callback"
              callback: "RESIDENCE_CAFE_BUTTON"
        - buttons:
            - id: "residence_fitness_spa"
              text: "💪 Residence Fitness & SPA"
              type: "callback"
              callback: "RESIDENCE_FITNESS_SPA_BUTTON"
        - buttons:
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "RESIDENCE_CAFE_BUTTON"
        target: "RESIDENCE_CAFE"
      - callback: "RESIDENCE_FITNESS_SPA_BUTTON"
        target: "RESIDENCE_FITNESS_SPA"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "MARKETS"
    text: |
      *🧺 Ближайшие рынки:*
      
      *Понедельник*
      📍[Рынок Ersoy](https://goo.gl/maps/6yhUhbb9Zpijy76JA) \(2\.5 км\)
      
      *Среда*
      📍[Рынок Beşkonaklılar](https://goo.gl/maps/RGH5rS8h7b2AMfCU6) \(500 м, до обеда\)
      📍[Рынок Demirgül](https://goo.gl/maps/uqxp8L4RscSe2jpM7) \(1\.7 км\)
      📍[Рынок Sütçüler](https://goo.gl/maps/yFbwpSdE4yNt7ojH7) \(3 км\)
      
      *Четверг*
      📍[Рынок Göksu](https://goo.gl/maps/WakaAx3KK4Vmz9ELA) \(1\.7 км\)
      📍[Рынок Sütçüler](https://goo.gl/maps/68DWmnXecWeFLbj4A) \(2\.2 км\)
      
      *Пятница*
      📍[Рынок Teomanpaşa](https://goo.gl/maps/nRZKwLYFBEuVV6BJ7) \(2\.5 км\)
      
      *Суббота*
      📍[Рынок Güneş](https://maps.app.goo.gl/AKJnVMJmheDE4g2dA) \(1\.4 км\)
    parse_mode: "MarkdownV2"
    disable_web_preview: true
    inline_keyboard:
      rows:
        - buttons:
            - id: "all_markets"
              text: "🧺 Другие рынки"
              type: "callback"
              callback: "ALL_MARKETS_BUTTON"
        - buttons:
            - id: "directions"
              text: "📍 Что рядом?"
              type: "callback"
              callback: "DIRECTIONS_BUTTON"
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "ALL_MARKETS_BUTTON"
        target: "ALL_MARKETS"
      - callback: "DIRECTIONS_BUTTON"
        target: "DIRECTIONS"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "ALL_MARKETS"
    text: |
      *Рынки:*
      
      📍 [Рынок SİTELER](https://goo.gl/maps/mYUuZawfTAU2) \(Понедельник\)
      📍 [Базар YENIDOĞAN](https://goo.gl/maps/DSfCL1JxACD2) \(Понедельник\)
      📍 [Рынок LİMAN](https://goo.gl/maps/nA23cv3x6sy) \(Вторник\)
      📍 [Базар BAHÇELİEVLER ](https://goo.gl/maps/cao3iJC1Dg72) \(Вторник\)
      📍 [Рынок YEŞİLBAHÇE](https://goo.gl/maps/nrT3xnr1f7P2) \(Среда\)
      📍 [Базар SİGORTA](https://goo.gl/maps/xpdVAv743nT2) \(Среда\)
      📍 [Рынок PAZAR ÖĞRETMENEVI](https://goo.gl/maps/6Ya5yxszQp92) \(Среда\)
      📍 [Базар DEDEMAN](https://goo.gl/maps/dRU5nL5AR752) \(Четверг\)
      📍 [Рынок BAHÇELİEVLER](https://goo.gl/maps/usNRD4oQRxH2) \(Четверг\)
      📍 [Базар GÜLVEREN](https://goo.gl/maps/MqwpmNKb7js) \(Четверг\)
      📍 [Рынок PERŞEMBE SEMT](https://goo.gl/maps/CEfKqRQTtbN2) \(Четверг\)
      📍 [Базар ALTINKUM](https://goo.gl/maps/4dpRFg4BPcq) \(Пятница\)
      📍 [Рынок GÜZELOBA](https://goo.gl/maps/DvVpef5xqZo) \(Пятница\)
      📍 [Рынок KIZILTOPRAK](https://goo.gl/maps/DGQKNLy5D7J2) \(Пятница\)
      📍 [Базар KIZILTOPRAK](https://goo.gl/maps/dRKoX3MWrrt) \(Пятница\)
      📍 [Базар KONUKSEVER](https://goo.gl/maps/fNqtj7SXdaS2) \(Суббота\)
      📍 [Рынок ZAFER](https://goo.gl/maps/jGzGvtS6q5L2) \(Суббота\)
      📍 [Базар PINARBAŞI](https://goo.gl/maps/FNhE4hF4fSN2) \(Воскресенье\)
      📍 [Рынок SİGORTA](https://goo.gl/maps/xpdVAv743nT2) \(Воскресенье\)
      📍 [Базар ÇAĞLAYAN](https://goo.gl/maps/DzBmxTcAdTx) \(Воскресенье\)
      📍 [Базар BAHÇELİEVLER](https://goo.gl/maps/usNRD4oQRxH2) \(Воскресенье\)
    parse_mode: "MarkdownV2"
    disable_web_preview: true
    inline_keyboard:
      rows:
        - buttons:
            - id: "markets"
              text: "🧺 Рынки"
              type: "callback"
              callback: "MARKETS_BUTTON"
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "MARKETS_BUTTON"
        target: "MARKETS"
      - callback: "DIRECTIONS_BUTTON"
        target: "DIRECTIONS"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "SHOPS"
    text: |
      *🍎 Ближайшие магазины*
      
      *Сетевики*
      📍 [Tahtakale](https://goo.gl/maps/trZCbiCLrSVKujrm7) \(900 м\)
      Магазин на все случаи жизни\. В том числе и продукты\. Магазин в 3 этажа\.

      🍌 [Sok](https://goo.gl/maps/bz15sV6peBEuQf9Z8) \(600 м\)
      🍌 [Bim](https://goo.gl/maps/ZEy8ZHqMTKCEMCdPA) \(650 м\)
      🍌 [A101](https://goo.gl/maps/UDmQrYRjrhWi7s7V7) \(650 м\)
      🍎 [Migros](https://goo.gl/maps/XXKsLLLMH61ojpnP8) \(1\.1 км\)
      В сети мигрос продается спиртное\.

      *Местные магазинчики*
      🍞 [Пекарня](https://goo.gl/maps/uKP6r6M9wbWnNzF4A) \(200 м\)
      🥩 [Мясной](https://goo.gl/maps/o4TSPiKd99Q7bUEEA) \(650 м\)
      🍷 [Спиртное Soylu Market](https://goo.gl/maps/o4TSPiKd99Q7bUEEA) \(650 м\)

      *Большие сетевые магазины*
      🛒 [Metro](https://goo.gl/maps/nCPd4qcC4ssJCk4E9) \(4\.4 км\)
      🛒 [5M Migros Kepez](https://goo.gl/maps/exzze46k7XUkAYPVA) \(10\.6 км\)
      🛒 [5M Migros Konyaaltı](https://goo.gl/maps/Z6PwMLrPprPGSwW47) \(10\.6 км\)
    parse_mode: "MarkdownV2"
    disable_web_preview: true
    inline_keyboard:
      rows:
        - buttons:
            - id: "directions"
              text: "🚀 Что рядом?"
              type: "callback"
              callback: "DIRECTIONS_BUTTON"
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "DIRECTIONS_BUTTON"
        target: "DIRECTIONS"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "SHOPPING_CENTERS"
    text: |
      *🛍 Торговые центры*
      
      📍 [Agora](https://goo.gl/maps/TshggHds8sAVBACV6) \(3\.8 км\)
      📍 [Mall of Antalya](https://g.page/MallOfAntalya) \(4\.8 км\)
      📍 [MarkAntalya](https://goo.gl/maps/BjqUUFpYRthDPZFJ9) \(6\.4 км\)
      📍 [Terra City](https://g.page/TerraCity) \(10\.3 км\)
      📍 [5M Migros AVM Konyaaltı](https://g.page/AntalyaMigrosAVM) \(10\.4 км\)
      
      📍 [Ozdilek Park](https://g.page/ozdilekparkantalya) \(6\.6 км\)
      📍 [Kipa AVM \(5M Migros Kepez\)](https://goo.gl/maps/FwRYmYLhETHsdX458) \(7\.0 км\)
      📍 [Erasta AVM](https://g.page/erastaantalyaavm) \(8\.3 км\)
      
      *Строительные*
      🛋 [IKEA](https://goo.gl/maps/zdLcFzx1tnq7EMXJ6) \(3\.9 км\)
      🪴 [Koctas](https://goo.gl/maps/qYwje1sAhz1SQ9ycA) \(5\.6 км\)
      🪚 [Bauhaus Kepez](https://goo.gl/maps/1VpdQAqd7giKGgbD8) \(8\.4 км\)
    parse_mode: "MarkdownV2"
    disable_web_preview: true
    inline_keyboard:
      rows:
        - buttons:
            - id: "directions"
              text: "🚀 Что рядом?"
              type: "callback"
              callback: "DIRECTIONS_BUTTON"
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "DIRECTIONS_BUTTON"
        target: "DIRECTIONS"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "PRINT_AND_PHOTO"
    text: |
      *Печать и Фото*
      
      📍 [HYT KIRTASİYE](https://goo.gl/maps/sxUvXUzyxyj5LXnD6) \(350 м\)
      
      📍 [Bella Color](https://goo.gl/maps/u3tRZcm2DXbC7Bh49) \(750 м\)
      \- Цветная печать 10 TL
      \- Биометрические фото 300 TL
      
      📍 [Fotokopi](https://goo.gl/maps/T6UtpDPoSSve3p58A) \(900 м\)
      📍 [Nebi Fotografcilik](https://g.page/NebiFoto) \(1\.2 км\)
    parse_mode: "MarkdownV2"
    disable_web_preview: true
    inline_keyboard:
      rows:
        - buttons:
            - id: "directions"
              text: "🚀 Что рядом?"
              type: "callback"
              callback: "DIRECTIONS_BUTTON"
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "DIRECTIONS_BUTTON"
        target: "DIRECTIONS"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "BARBER"
    text: |
      *Барбершопы*
      
      📍 [NZM Salonu](https://goo.gl/maps/yePJMmDWHJDqcCSS7)
      Стрижка \+ Мойка \+ Укладка 200 TL\.
      
      📍 [Yigit Erkek Kuaforu](https://goo.gl/maps/KUYj8pheja9Y2QST6)
      
      📍 [Barber by Ahmet](https://goo.gl/maps/uvpYxdxAJTF1bfYx5)
      
      📍 [Рядом с Migros](https://goo.gl/maps/PiBvkRPMak7bNo23A)
    parse_mode: "MarkdownV2"
    disable_web_preview: true
    inline_keyboard:
      rows:
        - buttons:
            - id: "directions"
              text: "📍 Что рядом?"
              type: "callback"
              callback: "DIRECTIONS_BUTTON"
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "DIRECTIONS_BUTTON"
        target: "DIRECTIONS"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "TAX_OFFICE"
    text: |
      *💸 Налоговая \(Vergi Dairesi\)*
      
      ℹ️ *Тут можно:*
      \- Получить Турецкий налоговый номер ИНН
      \- Оплатить пошлину за разблокировку телефона
      \- Оплатить штраф за авто на иностранных номерах
      
      📍 [Antalya Vergi Dairesi](https://goo.gl/maps/qtCJEGf4cYfD1QXR6) \(7\.7 км\)
    parse_mode: "MarkdownV2"
    disable_web_preview: true
    inline_keyboard:
      rows:
        - buttons:
            - id: "directions"
              text: "📍 Что рядом?"
              type: "callback"
              callback: "DIRECTIONS_BUTTON"
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "DIRECTIONS_BUTTON"
        target: "DIRECTIONS"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "POST_OFFICE"
    text: |
      *✉️ Почта \(PTT\)*
      
      📍 [PTT Yesilirmak](https://goo.gl/maps/sCWvbXQSn5nhR1U48) \(2\.6 км\)
      Почта нашего комплекса, сюда приходят икаметы
      
      📍 [PTT Teomanpasa](https://goo.gl/maps/xq1qT8CjHqhzXtKx9) \(2\.1 км\)
      📍 [PTT Sutculer](https://goo.gl/maps/nd8XwFx2EbUYSCj57) \(2\.9 км\)
      
      ℹ️ Где еще можно оплатить коммунальные услуги читайте в разделе:
      🌟 Все о Ekpa \-\> 💰 Как Оплатить?
    parse_mode: "MarkdownV2"
    disable_web_preview: true
    inline_keyboard:
      rows:
        - buttons:
            - id: "directions"
              text: "📍 Что рядом?"
              type: "callback"
              callback: "DIRECTIONS_BUTTON"
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "DIRECTIONS_BUTTON"
        target: "DIRECTIONS"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "CITY_HALL"
    text: |
      *🏛 Belediye \(Муниципалитет\)*
      
      ℹ️ В данном заведении можно получить справку *Нумаратаж* \(Numarataj\), необходимую для получения ВНЖ
      ⚡️ На первом этаже можно сделать копии документов за 1 TL
      
      📍 [Kepez Belediye](https://goo.gl/maps/5WBP63uMR5dCa1HcA) \(3\.5 км\)
    parse_mode: "MarkdownV2"
    disable_web_preview: true
    inline_keyboard:
      rows:
        - buttons:
            - id: "directions"
              text: "📍 Что рядом?"
              type: "callback"
              callback: "DIRECTIONS_BUTTON"
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "DIRECTIONS_BUTTON"
        target: "DIRECTIONS"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "POPULATION_OFFICE"
    text: |
      *🧑‍💼 Nufus \(Министерство регистрации населения\)*
      
      ℹ️ В данном заведении оформляют Тапу, прописывают Турецких граждан, регистрируют новорожденных и решают другие вопросы народонаселения\.
      ⚠️ Иностранцы должны прописываться в Goc, а не Nufus\.
      
      📍 [Kepez Nufus](https://goo.gl/maps/1u4SiTYfYBVbRNFs8) \(3\.5 км\)
    parse_mode: "MarkdownV2"
    disable_web_preview: true
    inline_keyboard:
      rows:
        - buttons:
            - id: "directions"
              text: "📍 Что рядом?"
              type: "callback"
              callback: "DIRECTIONS_BUTTON"
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "DIRECTIONS_BUTTON"
        target: "DIRECTIONS"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "MIGRATION_OFFICE"
    text: |
      *👮 Goc Idaresi \(Управление миграции Анталии\)*
      
      1️⃣ Здесь нужно сделать прописку\.
      2️⃣ Здесь происходит рандеву \(подача на ВНЖ\) и решаются все вопросы связанные с ВНЖ\.
      3️⃣ Сюда могут позвать на отпечатки пальцев тех, кто еще это не сделал\.
      
      📍 [Goc Idaresi](https://goo.gl/maps/Q46vs5Dj9ipu32cS9) \(8\.1 км\)
    parse_mode: "MarkdownV2"
    disable_web_preview: true
    inline_keyboard:
      rows:
        - buttons:
            - id: "directions"
              text: "📍 Что рядом?"
              type: "callback"
              callback: "DIRECTIONS_BUTTON"
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "DIRECTIONS_BUTTON"
        target: "DIRECTIONS"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "RESIDENCE_CAFE"
    text: "*☕️ Residence Cafe*"
    parse_mode: "MarkdownV2"
    inline_keyboard:
      rows:
        - buttons:
            - id: "residence_cafe_menu"
              text: "📋 Меню"
              type: "url"
              url: "https://example.com/menu"
        - buttons:
            - id: "residence_cafe_wifi"
              text: "📶 WiFi"
              type: "callback"
              callback: "RESIDENCE_CAFE_WIFI_BUTTON"
        - buttons:
            - id: "directions_site"
              text: "🗺 Карта объектов"
              type: "callback"
              callback: "DIRECTIONS_SITE_BUTTON"
        - buttons:
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "RESIDENCE_CAFE_WIFI_BUTTON"
        target: "RESIDENCE_CAFE_WIFI"
      - callback: "DIRECTIONS_SITE_BUTTON"
        target: "DIRECTIONS_SITE"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "RESIDENCE_CAFE_WIFI"
    text: |
      *📶 WiFi Residence Cafe*
      
      Пароль: `residencecafe`
    parse_mode: "MarkdownV2"
    inline_keyboard:
      rows:
        - buttons:
            - id: "residence_cafe"
              text: "☕️ Residence Cafe"
              type: "callback"
              callback: "RESIDENCE_CAFE_BUTTON"
        - buttons:
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "RESIDENCE_CAFE_BUTTON"
        target: "RESIDENCE_CAFE"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"

  - id: "RESIDENCE_FITNESS_SPA"
    text: "*💪 Residence Fitness & SPA*"
    parse_mode: "MarkdownV2"
    inline_keyboard:
      rows:
        - buttons:
            - id: "directions_site"
              text: "🗺 Карта объектов"
              type: "callback"
              callback: "DIRECTIONS_SITE_BUTTON"
        - buttons:
            - id: "main_menu"
              text: "🏠 В главное меню"
              type: "callback"
              callback: "MAIN_MENU_BUTTON"
    navigation:
      - callback: "DIRECTIONS_SITE_BUTTON"
        target: "DIRECTIONS_SITE"
      - callback: "MAIN_MENU_BUTTON"
        target: "MAIN_MENU"
