bot:
  username: "EkpaAntalyaBot"
  token: "5650858881:AAHpuXQ7qUBgwy-pinis-u1uYkyT-ZXm7Ic"  # TEST TOKEN

content:
  directory: "configs/content"

health:
  enabled: true
  port: 8080
  address: "0.0.0.0"
