name: Build and Publish Services

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  GO_VERSION: '1.25.0'

jobs:
  set-vars:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    outputs:
      go_version: ${{ steps.set-go-version.outputs.go_version }}
    steps:
      - id: set-go-version
        run: echo "go_version=${GO_VERSION}" >> $GITHUB_OUTPUT

  test:
    needs: [ set-vars ]
    uses: ./.github/workflows/go-test.yml
    with:
      go-version: ${{ needs.set-vars.outputs.go_version }}
    secrets: inherit

  build:
    needs: [ set-vars ]
    uses: ./.github/workflows/go-build.yml
    with:
      services: '["bot"]'
      architectures: '["amd64", "arm64"]'
      go-version: ${{ needs.set-vars.outputs.go_version }}
    secrets: inherit

  publish:
    needs: [ test, build ]
    if: github.event_name == 'push'
    uses: ./.github/workflows/docker-publish.yml
    with:
      services: '["auth"]'
    secrets: inherit