name: Go Test

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
    secrets:
      BUILD_GITHUB_TOKEN:
        required: true

jobs:
  test:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-go
        with:
          go-version: ${{ inputs.go-version }}

      - name: 🔨 Compile tests
        run: go list ./... | xargs -I {} go test -c {} -o /dev/null

      - name: 🧪 Run tests
        run: go test -v ./...